# Generated by Django 5.2.5 on 2025-08-21 18:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('year', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('age_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(default=12345678, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('user_full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('language', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_ban', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Showed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('showed_time', models.DateTimeField(auto_now_add=True)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showed', to='Cinema.cinema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showed', to='Users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='Cinema.cinema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='Users.user')),
            ],
        ),
    ]
