# Generated by Django 5.2.5 on 2025-08-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
