# Generated by Django 5.2.5 on 2025-08-20 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_favorite_rating_alter_info_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='age_limit',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
