# Generated by Django 5.2.5 on 2025-08-20 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_info_age_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='age_limit',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
