# Generated by Django 5.2.5 on 2025-08-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_info_age_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='cinema_code',
            field=models.TextField(unique=True),
        ),
    ]
