# Generated by Django 5.2.5 on 2025-08-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cinema_url', models.TextField()),
                ('cinema_code', models.TextField(unique=True)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('next', models.IntegerField(blank=True, null=True)),
                ('previous', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
